# Reference: https://build-cpp.github.io/cmkr/cmake-toml


[target.UnknownUtils-LLVMDemangle]
type = "library"
include-directories = ["../include"]
sources = ["*.cpp", "*.hpp", "*.h"]
compile-features = ["cxx_std_20"]



